import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'
import ProgressBarProvider from '@/components/ProgressBarProvider'
import localFont from 'next/font/local'

const myFont = localFont({
  src: '../public/fonts/Afacad-Regular.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Crickify',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={myFont.className}>
      <body>
        <ProgressBarProvider>
          <Header />
          {children}
        </ProgressBarProvider>
        <div className="fixed left-0 top-0 -z-10 h-full w-full">
          <div className="absolute inset-0 -z-10 h-full w-full bg-white bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]">
          </div>
        </div>
      </body>
    </html>
  )
}
