import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'
import ProgressBarProvider from '@/components/ProgressBarProvider'
import localFont from 'next/font/local'

const myFont = localFont({
  src: '../public/fonts/Afacad-Regular.ttf',
  display: 'swap',
})
 
export const metadata: Metadata = {
  title: 'Crickify',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={myFont.className}>
      <body>
        <ProgressBarProvider>
          <Header />
          {children}
        </ProgressBarProvider>
      </body>
    </html>
  )
}
